apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  name: thanos-querier-example-coo-thanos
  namespace: project-a
spec:
  ports:
  - name: proxy
    port: 8888
    protocol: TCP
    targetPort: oauth-proxy
  - name: http
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    app.kubernetes.io/instance: thanos-querier-example-coo-thanos
  sessionAffinity: None
  type: ClusterIP
